<a href="https://colab.research.google.com/github/icy-agarwal/AIML/blob/main/DAY2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
a[0]

np.int64(1)

In [ ]:
a[1]

np.int64(2)

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
import sys

In [ ]:
l = range(1000)
print(sys.getsizeof(5)*len(l)) #this is to get the size of list

28000


In [ ]:
array = np.arange(1000)
print(array.size*array.itemsize) #array size is total lenght and array item size is size of one element in array

8000


In [ ]:
import time

In [ ]:
SIZE = 1000

L1 = range(SIZE)
L2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python list
start = time.time()
result = [(x+y) for x, y in zip(L1, L2)]
print("python list took: ", (time.time()-start)*1000)

#python array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

python list took:  0.3712177276611328
numpy took:  0.18215179443359375


In [ ]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b.ndim

2

In [ ]:
a1.ndim

1

In [ ]:
b.itemsize

8

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c = np.array([[1, 2], [3, 4], [5, 6]], dtype = np.float64)

In [ ]:
c.itemsize

8

In [ ]:
c

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
c.shape

(3, 2)

In [ ]:
d = np.array([[1, 2], [3, 4], [5, 6]], dtype = complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
np.zeros( (3, 4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (3, 4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1, 5, 2) #step of 2 (last number)

array([1, 3])

In [ ]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
d.reshape(2, 3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [ ]:
b.shape

(3, 2)

In [ ]:
b.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
b.ravel() #returns new array does not change original array

array([1, 2, 3, 4, 5, 6])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b.min()

np.int64(1)

In [ ]:
c.max()

np.float64(6.0)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
a.sum()

np.int64(6)

In [ ]:
b.sum(axis=0) #axis zero is top to down and axis 1 is left to right

array([ 9, 12])

In [ ]:
b.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(b)

np.float64(1.707825127659933)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b + c

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.]])

In [ ]:
a.dot(b)

array([22, 28])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a[-1]

np.int64(3)

In [ ]:
a[0:2]

array([1, 2])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
e

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
e[1, 2]

np.int64(3)

In [ ]:
e[0:2, 2] #0:2 -> 0 and 1st row. 2 means column.

array([8, 3])

In [ ]:
e[-1, 0:2]

array([9, 3])

In [ ]:
e[:, 1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
for row in e:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
for cell in e.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
f = np.arange(6).reshape(3,2)

In [ ]:
f

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.vstack((b, f)) #vertical stacking

array([[1, 2],
       [3, 4],
       [5, 6],
       [0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
g = np.hstack((b, f)) #horizontal stacking

In [ ]:
g

array([[1, 2, 0, 1],
       [3, 4, 2, 3],
       [5, 6, 4, 5]])

In [ ]:
h = np.arange(30).reshape(2, 15)
h

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
result = np.hsplit(h, 3)

In [ ]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [ ]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
res = np.vsplit(h, 2)

In [ ]:
res[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
res[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])